services:
  - docker
env:
  matrix:
  - VERSION=15.0.2
  - VERSION=15.0.1
  - VERSION=15.0.0
  - VERSION=14.0.6
  - VERSION=14.0.5
  - VERSION=14.0.4
  - VERSION=14.0.3
  - VERSION=14.0.2
  - VERSION=14.0.1
  - VERSION=14.0.0
  - VERSION=13.0.9
  - VERSION=13.0.8
  - VERSION=13.0.7
  - VERSION=13.0.6
  - VERSION=13.0.5
  - VERSION=13.0.4
  - VERSION=13.0.3
  - VERSION=13.0.2
  - VERSION=13.0.1
  - VERSION=13.0.0
before_install:
  - docker --version
  - docker-compose --version
script:
  - docker-compose -f ./nc/docker-compose.test.yml up -d --build
  - docker container ls
  - docker inspect --format="{{json .State.Health.Status}}" nc_sut_1
  - |
    SUT_HEALTH="notok" && counter=0
    while [ $SUT_HEALTH != "healthy" ] && [ $counter -le 30 ]; do
    SUT_HEALTH=$(docker inspect --format="{{json .State.Health.Status}}" nc_sut_1)
    sleep 2
    counter=$(( $counter + 1 ))
    done
  - docker inspect --format="{{json .State.Health.Status}}" nc_sut_1
after_script:
  - docker container ls
