services:
  - docker
env:
  matrix:
  - VERSION=15.0.2
  - VERSION=15.0.1
before_install:
  - sudo apt-get install -y whois
  - docker --version
  - docker-compose --version
  - export NC_PASS_CI=`mkpasswd`
  - export DB_PASS_CI=`mkpasswd`
  - export MYSQL_ROOT_PASSWORD_CI=`mkpasswd`
script:
  - docker-compose -f ./nc/docker-compose.test.yml up -d --build
  - docker container ls
  - docker inspect --format="{{json .State.Health.Status}}" nc_sut_1
  - |
    SUT_HEALTH="notok" && counter=0
    while [ $SUT_HEALTH != "healthy" ] && [ $counter -le 30 ]; do
    SUT_HEALTH=$(docker inspect --format="{{json .State.Health.Status}}" nc_sut_1)
    sleep 2
    counter=$(( $counter + 1 ))
    done
  - docker inspect --format="{{json .State.Health.Status}}" nc_sut_1
after_script:
  - docker container ls
