version: 2
jobs:
  build:
#    machine: true
    docker: 
      - image: docker:stable-git
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - setup_remote_docker
      - run: |
          export NC_PASS_CI=test
          export DB_PASS_CI=test
          export MYSQL_ROOT_PASSWORD_CI=test
          export VERSION=13.0.9
      - run: |
          docker-compose -f ./nc/docker-compose.test.yml up -d --build
