version: 2.1
orbs:
  anchore-engine: anchore/anchore-engine@1.0.0
workflows:
  version: 2.1
    scan_image:
      jobs:
        - anchore/image_scan:
            image_name: tob123/nextcloud-staging:15
            timeout: '300'
