version: 2
jobs:
  build:
#    machine: true
    docker: 
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          export NC_PASS_CI=test
          export DB_PASS_CI=test
          export MYSQL_ROOT_PASSWORD_CI=test
          export VERSION=13.0.9
      - run: |
          docker-compose -f ./nc/docker-compose.test.yml up -d --build
