version: 2.1
orbs:
  anchore-engine: anchore/anchore-engine@1.1.0
workflows:
  scan_image:
    jobs:
      - anchore/image_scan:
          image_name: tob123/nextcloud-staging:15
          timeout: '300'
